version: "2"
services:
  mysql-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tp-delivery
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password